eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.6:8761/eureka/
    instance:
#       hostname: localhost
      preferIpAddress: true
